DROP INDEX longitude_index_location;
DROP INDEX widht_index_location;
DROP INDEX longitude_index_anomaly;
DROP INDEX widht_index_anomaly;
DROP INDEX name_index_human;
DROP INDEX surname_index_human;
DROP INDEX name_index_eqp;
DROP INDEX name_index_operation;
DROP INDEX name_index_location;